# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatosNota.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatosNota(object):
    def setupUi(self, DatosNota):
        DatosNota.setObjectName("DatosNota")
        DatosNota.resize(380, 245)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        DatosNota.setFont(font)
        self.centralwidget = QtWidgets.QWidget(DatosNota)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 20, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.confirmar.setGeometry(QtCore.QRect(240, 180, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.confirmar.setFont(font)
        self.confirmar.setCheckable(False)
        self.confirmar.setAutoDefault(False)
        self.confirmar.setDefault(False)
        self.confirmar.setFlat(False)
        self.confirmar.setObjectName("confirmar")
        self.cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.cancelar.setGeometry(QtCore.QRect(100, 180, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancelar.setFont(font)
        self.cancelar.setCheckable(False)
        self.cancelar.setAutoDefault(False)
        self.cancelar.setDefault(False)
        self.cancelar.setFlat(False)
        self.cancelar.setObjectName("cancelar")
        self.correo = QtWidgets.QLineEdit(self.centralwidget)
        self.correo.setGeometry(QtCore.QRect(100, 50, 271, 20))
        self.correo.setObjectName("correo")
        self.nota = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.nota.setGeometry(QtCore.QRect(100, 130, 62, 22))
        self.nota.setWrapping(True)
        self.nota.setDecimals(1)
        self.nota.setMaximum(5.0)
        self.nota.setProperty("value", 3.0)
        self.nota.setObjectName("nota")
        self.actividad = QtWidgets.QComboBox(self.centralwidget)
        self.actividad.setGeometry(QtCore.QRect(100, 90, 271, 22))
        self.actividad.setObjectName("actividad")
        DatosNota.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DatosNota)
        self.statusbar.setObjectName("statusbar")
        DatosNota.setStatusBar(self.statusbar)

        self.retranslateUi(DatosNota)
        QtCore.QMetaObject.connectSlotsByName(DatosNota)

    def retranslateUi(self, DatosNota):
        _translate = QtCore.QCoreApplication.translate
        DatosNota.setWindowTitle(_translate("DatosNota", "Editar Nota"))
        self.label.setText(_translate("DatosNota", "Estudiante: "))
        self.label_2.setText(_translate("DatosNota", "Actividad: "))
        self.label_3.setText(_translate("DatosNota", "Nota:"))
        self.label_4.setText(_translate("DatosNota", "EDITAR NOTA"))
        self.confirmar.setText(_translate("DatosNota", "CONFIRMAR"))
        self.cancelar.setText(_translate("DatosNota", "CANCELAR"))
