# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatosInasistencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatosInasistencia(object):
    def setupUi(self, DatosInasistencia):
        DatosInasistencia.setObjectName("DatosInasistencia")
        DatosInasistencia.resize(456, 201)
        self.centralwidget = QtWidgets.QWidget(DatosInasistencia)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.correo = QtWidgets.QLineEdit(self.centralwidget)
        self.correo.setGeometry(QtCore.QRect(170, 40, 271, 20))
        self.correo.setObjectName("correo")
        self.fecha = QtWidgets.QDateEdit(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(170, 90, 110, 22))
        self.fecha.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.fecha.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.fecha.setCalendarPopup(True)
        self.fecha.setDate(QtCore.QDate(2020, 12, 1))
        self.fecha.setObjectName("fecha")
        self.cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.cancelar.setGeometry(QtCore.QRect(170, 140, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancelar.setFont(font)
        self.cancelar.setCheckable(False)
        self.cancelar.setAutoDefault(False)
        self.cancelar.setDefault(False)
        self.cancelar.setFlat(False)
        self.cancelar.setObjectName("cancelar")
        self.confirmar = QtWidgets.QPushButton(self.centralwidget)
        self.confirmar.setGeometry(QtCore.QRect(310, 140, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.confirmar.setFont(font)
        self.confirmar.setCheckable(False)
        self.confirmar.setAutoDefault(False)
        self.confirmar.setDefault(False)
        self.confirmar.setFlat(False)
        self.confirmar.setObjectName("confirmar")
        DatosInasistencia.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DatosInasistencia)
        self.statusbar.setObjectName("statusbar")
        DatosInasistencia.setStatusBar(self.statusbar)

        self.retranslateUi(DatosInasistencia)
        QtCore.QMetaObject.connectSlotsByName(DatosInasistencia)

    def retranslateUi(self, DatosInasistencia):
        _translate = QtCore.QCoreApplication.translate
        DatosInasistencia.setWindowTitle(_translate("DatosInasistencia", "Registrar Inasistencias"))
        self.label.setText(_translate("DatosInasistencia", "Fecha:"))
        self.label_2.setText(_translate("DatosInasistencia", "Correo Estudiante:"))
        self.cancelar.setText(_translate("DatosInasistencia", "CANCELAR"))
        self.confirmar.setText(_translate("DatosInasistencia", "CONFIRMAR"))
